version: "3"
services:
  app:
    image: beslow/goblog:latest
    ports:
      - "80:80"
    # sleep 8 second to wait that mysql is really ready for connection.
    command: /bin/sh -c "sleep 8 && ./goblog -db:create && ./goblog -db:migrate && ./goblog -db:seed && ./goblog"
    depends_on:
      - db
      - redis
    networks: 
      - goblog-net
  db:
    image: mysql:5.7
    hostname: db
    ports: 
      - "13306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    networks:
      - goblog-net
  redis:
    image: redis:6.0.16-bullseye
    command: redis-server --appendonly yes
    restart: unless-stopped
    ports:
      - "16379:6379"
    volumes:
      - /var/lib/data:/data  
    networks:
      - goblog-net  
networks:
  goblog-net:   
