FROM alpine:3.14

RUN apk add wait4x

WORKDIR /app

COPY goblog adm.ini /app/

COPY config.yml.example /app/config.yml

COPY redis.yml.example /app/redis.yml

COPY sentry.yml.example /app/sentry.yml

RUN chmod +x /app/goblog

# CMD ["./goblog"]
