version: "3"
services:
  app:
    build: .
    ports:
      - "8080:80" 
    command: /bin/sh -c "wait4x tcp db:3306 -t 30s && wait4x tcp redis:6379 -t 30s && ./goblog -db:create && ./goblog -db:migrate && ./goblog -db:seed && ./goblog"
    depends_on:
      - db
      - redis
    networks: 
      - goblog-net
  db:
    image: mysql:5.7
    hostname: db
    ports: 
      - "13306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    networks:
      - goblog-net
  redis:
    image: redis:6.0.16-bullseye
    command: redis-server --appendonly yes
    restart: unless-stopped
    volumes:
      - /var/lib/data:/data  
    networks:
      - goblog-net  
networks:
  goblog-net:  
