// This file is generated by GoAdmin CLI adm.
package tables

import "github.com/GoAdminGroup/go-admin/plugins/admin/modules/table"

// Generators is a map of table models.
//
// The key of Generators is the prefix of table info url.
// The corresponding value is the Form and Table data.
//
// http://{{config.Domain}}:{{Port}}/{{config.Prefix}}/info/{{key}}
//
// example:
//

// "history_educations" => http://localhost:9033/admin/info/history_educations
// "posts" => http://localhost:9033/admin/info/posts
// "categories" => http://localhost:9033/admin/info/categories
// "consts" => http://localhost:9033/admin/info/consts
//
// example end

var Generators = map[string]table.Generator{
	"history_works":      GetHistoryWorksTable,
	"test_users":         GetTestUsersTable,
	"history_educations": GetHistoryEducationsTable,
	"posts":              GetPostsTable,
	"categories":         GetCategoriesTable,
	"consts":             GetConstsTable,

	// generators end
}
